name = "emailsignaturegenerator"
main = "_worker.js"
compatibility_date = "2025-04-01"

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = true

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "email-sig-photos"

[[ratelimits]]
name = "RATE_LIMIT"
namespace_id = "1001"

[ratelimits.simple]
limit = 25
period = 60
